name: "Deploy Documents Latest"

on:
  push:
    branches:
    - test-actions

env:
  DOCFX_FILE: docfx_tizen_docs.json
  DEPLOY_BRANCH: gh-pages
  CACHE_NAME: docfx-gh-pages-site

jobs:

  build:
    runs-on: [self-hosted, linux, x64]
    container:
      image: tizendotnet/tizenfx-build-worker:2.4
      options: --ulimit nofile=10240:10240

    steps:
    - uses: actions/checkout@v3
      with:
        repository: TizenAPI/TizenFX-Docs

    - name: Checkout TizenFX sources
      run: |
        ./build_master.sh clone
    - name: Cache DocFX output
      id: cache-site
      uses: actions/cache@v2
      with:
        path: _site
        key: ${{ env.CACHE_NAME }}-${{ hashFiles('repos/commits') }}

    - name: Build Documents
      if: steps.cache-site.outputs.cache-hit != 'true'
      run: |
        ./build_master.sh restore
        ./build_master.sh build
        ./build_master.sh index
    - name: Archive Artifacts
      run: |
        tar cfz site.tar.gz _site/
    - uses: actions/upload-artifact@v2
      with:
        name: documents
        path: site.tar.gz

  deploy:
    needs: [build]
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: documents

    - name: Extract Artifacts
      run: |
        tar xfz site.tar.gz
    - name: Deploy GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        keep_files: true
        publish_branch: ${{ env.DEPLOY_BRANCH }}
        user_name: 'TizenAPI-Bot'
        user_email: 'tizenapi@samsung.com'
        full_commit_message: 'Update documents'