name: "Deploy Documents Test"

on:
  push:
    branches:
    - test-actions

jobs:

  build:
    runs-on: [self-hosted, linux, x64]
    container:
      image: tizendotnet/tizenfx-build-worker:2.2
      options: --ulimit 65535

    steps:
    - uses: actions/checkout@v2
      with:
        repository: TizenAPI/TizenFX-Docs
        ref: devel

    - name: Checkout TizenFX sources
      run: |
        ulimit -a
        cat /proc/sys/fs/file-max
        ./build_12.sh clone

    - name: Cache DocFX output
      id: cache-site
      uses: actions/cache@v2
      with:
        path: _site
        key: docfx-gh-pages-site-${{ hashFiles('repos/commits') }}

    - name: Build Documents
      if: steps.cache-site.outputs.cache-hit != 'true'
      run: |
        ./build_12.sh restore
        ./build_12.sh build
        ./build_12.sh index
